name: database
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^1.3.1
  flutter_form_builder: ^3.3.4
  flutter_datetime_picker: ^1.2.1
  flutter_country_picker: ^0.1.4
  frideos: ^0.6.1
  image_picker: ^0.6.0+9
  font_awesome_flutter: ^8.2.0
  flutter_svg: ^0.14.0
  flutter_tagging: ^1.1.0
  dotted_border: ^0.1.1
  http: ^0.12.0+2
  flutter_typeahead: ^1.6.1
  sqflite: ^1.1.6
  path_provider: any
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/profile.png
    - images/icons/dashboard.svg
    - images/icons/user.svg
    - images/sonatech.png
    - images/icons/location.svg
    - images/icons/vector.svg
    - images/icons/sonatech_png.png
    - images/icons/contact.png
    - images/icons/ellipse.png
    - images/delta.png
    - images/female.png
    - images/female_r.png
    - images/male.png
    - images/computer.png
